all:
	g++ CRAFT_Quadruple_MPI_RNG.cpp --std=c++11 -Wall -O3 -o CRAFT_Quadruple_MPI_RNG -l msmpi -L "D:\Microsoft SDKs\MPI\Lib\x64" -I "D:\Microsoft SDKs\MPI\Include"
clean:
	rm -f *.o CRAFT_Quadruple_MPI
